version: '3'

services:

  locustmaster:
    image: locustio/locust
    container_name: locustmaster
    build: .
    ports:
      - "8086:8086"
    volumes:
      - ./code:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master --web-port 8086  # Specify port 8086 for web app
    networks:
      - network1
  
  locustworker:
    image: locustio/locust
    container_name: locustworker
    build: .
    volumes:
      - ./code:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host locustmaster
    networks:
      - network1

networks:
    # We use external network because we are using the data given by the "project 2" who has their own network.
    # First you need to identify the network name with the following command: `docker network ls`
    # Then add the network name after "name" and add "external" to "true"
    # This will make understand this docker compose that you are using and external network that is available
  network1:
    name: project_2_project_network
    external: true